/**
* Party maker API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapi.example.model


import com.google.gson.annotations.SerializedName
import java.io.Serializable

/**
 * 
 * @param id 
 * @param email 
 * @param name 
 * @param imageId 
 * @param phone 
 */

data class WebAppUpdateUserRequestDto (
    @SerializedName("id")
    val id: java.util.UUID? = null,
    @SerializedName("email")
    val email: kotlin.String? = null,
    @SerializedName("name")
    val name: kotlin.String? = null,
    @SerializedName("imageId")
    val imageId: java.util.UUID? = null,
    @SerializedName("phone")
    val phone: kotlin.String? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

