/**
* Party maker API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.serma.dionysus.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
* 
* Values: _1,_2,_4,_8
*/

@Serializable
enum class EUserEventRole(val value: kotlin.Int) {


    @SerialName(value = "1")
    _1(1),

    @SerialName(value = "2")
    _2(2),

    @SerialName(value = "4")
    _4(4),

    @SerialName(value = "8")
    _8(8);


    /**
    This override toString avoids using the enum var name and uses the actual api value instead.
    In cases the var name and value are different, the client would send incorrect enums to the server.
    **/
    override fun toString(): String {
        return value.toString()
    }
}

