/**
* Party maker API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.serma.dionysus.model

import kotlinx.serialization.SerialName
import java.io.Serializable

/**
 * 
 * @param type 
 * @param title 
 * @param status 
 * @param detail 
 * @param instance 
 */

data class ProblemDetails (
    @SerialName("type")
    val type: kotlin.String? = null,
    @SerialName("title")
    val title: kotlin.String? = null,
    @SerialName("status")
    val status: kotlin.Int? = null,
    @SerialName("detail")
    val detail: kotlin.String? = null,
    @SerialName("instance")
    val instance: kotlin.String? = null
) :Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

