/**
* Party maker API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.serma.dionysus.model

import kotlinx.serialization.SerialName
import java.io.Serializable

/**
 * 
 * @param id 
 * @param name 
 * @param date 
 * @param address 
 * @param latitude 
 * @param longitude 
 * @param typeEvent 
 * @param totalBudget 
 * @param participaties 
 */

data class WebAppEventDto (
    @SerialName("id")
    val id: java.util.UUID? = null,
    @SerialName("name")
    val name: kotlin.String? = null,
    @SerialName("date")
    val date: java.time.OffsetDateTime? = null,
    @SerialName("address")
    val address: kotlin.String? = null,
    @SerialName("latitude")
    val latitude: kotlin.Double? = null,
    @SerialName("longitude")
    val longitude: kotlin.Double? = null,
    @SerialName("typeEvent")
    val typeEvent: ETypeEvent? = null,
    @SerialName("totalBudget")
    val totalBudget: kotlin.Double? = null,
    @SerialName("participaties")
    val participaties: kotlin.collections.List<WebAppUserEventDto>? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

