/**
* Party maker API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.serma.dionysus.model

import kotlinx.serialization.SerialName
import java.io.Serializable

/**
 * 
 * @param id 
 * @param wrongCredentials 
 * @param username 
 * @param userRole 
 * @param token 
 * @param expiresTime 
 * @param refreshToken 
 */

data class WebAppAuthenticateResponceDto (
    @SerialName("id")
    val id: java.util.UUID? = null,
    @SerialName("wrongCredentials")
    val wrongCredentials: kotlin.Boolean? = null,
    @SerialName("username")
    val username: kotlin.String? = null,
    @SerialName("userRole")
    val userRole: EUserRole? = null,
    @SerialName("token")
    val token: kotlin.String? = null,
    @SerialName("expiresTime")
    val expiresTime: kotlin.Long? = null,
    @SerialName("refreshToken")
    val refreshToken: kotlin.String? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

