/**
* Party maker API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.serma.dionysus.model

import kotlinx.serialization.SerialName
import java.io.Serializable

/**
 * 
 * @param id 
 * @param username 
 * @param userRole 
 * @param email 
 * @param imageId 
 * @param phone 
 */

data class WebAppAuthUserResponseDto (
    @SerialName("id")
    val id: java.util.UUID? = null,
    @SerialName("username")
    val username: kotlin.String? = null,
    @SerialName("userRole")
    val userRole: EUserRole? = null,
    @SerialName("email")
    val email: kotlin.String? = null,
    @SerialName("imageId")
    val imageId: java.util.UUID? = null,
    @SerialName("phone")
    val phone: kotlin.String? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

