/**
* Party maker API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.serma.dionysus.model


import kotlinx.serialization.SerialName
import java.io.Serializable

/**
 * 
 * @param id 
 * @param fileId 
 */

data class WebAppImageResponseDto (
    @SerialName("id")
    val id: java.util.UUID? = null,
    @SerialName("fileId")
    val fileId: java.util.UUID? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

